# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4de3a04e698468a49aeda3cdebece749253f675eff8f9f6dda92cc63179d31a4d1d9b56b6b4bdd2bf0e98b869a2f55855c6403ffdac9a1d2e597a3dc3a9d9ec3

test:
  secret_key_base: 930e637d0a24208bb7d57332f075dc2d07b4830894de3b61b72c2ba01c7d0c13778d0c0cfcfcf8353dae69feeb1592b5e76f8c2bd500dec1d3d645e6b7d8c68a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
